// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	"soul"
	mock "github.com/stretchr/testify/mock"
)

// NoteRepository is an autogenerated mock type for the NoteRepository type
type NoteRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: note
func (_m *NoteRepository) Create(note *soul.Note) error {
	ret := _m.Called(note)

	var r0 error
	if rf, ok := ret.Get(0).(func(*soul.Note) error); ok {
		r0 = rf(note)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *NoteRepository) GetAll() ([]soul.Note, error) {
	ret := _m.Called()

	var r0 []soul.Note
	if rf, ok := ret.Get(0).(func() []soul.Note); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]soul.Note)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: note
func (_m *NoteRepository) Update(note *soul.Note) error {
	ret := _m.Called(note)

	var r0 error
	if rf, ok := ret.Get(0).(func(*soul.Note) error); ok {
		r0 = rf(note)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
